spring:
  profiles:
    active: local

devHost: localhost:3306
devDatabase: comarket
devUser: ENC(7qCN+Qamt7gEaZM9Gc84Nd31Cw8mBIpgLhdiItlzDizcciEflviQXA==)
devPwd: ENC(7qCN+Qamt7gEaZM9Gc84Nd31Cw8mBIpgLhdiItlzDizcciEflviQXA==)
ddlAuto: none

---
spring:
  mail:
    host: smtp.gmail.com
    username: ENC(7qCN+Qamt7gEaZM9Gc84Nd31Cw8mBIpgLhdiItlzDizcciEflviQXA==)
    password: ENC(X0FxUISMet+c27+xXAc+kEUGkQp+BB/Y091abr8u2v6AWrVsF+D7Ig==)
    properties:
      mail:
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    properties:
      hibernate:
        show-sql: true
        physical_naming_strategy: com.grapheople.comarket.config.jpa.JpaPhysicalNamingStrategy
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: ${ddlAuto}
        id:
          new_generator_mappings: false
      hbm2ddl:
        auto: ${ddlAuto}

datasource:
  url: jdbc:mysql://${devHost}/${devDatabase}?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useAffectedRows=true&rewriteBatchedStatements=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Seoul
  username: ${devUser}
  password: ${devPwd}
  driverClassName: com.mysql.cj.jdbc.Driver
  initialSize: 8
  maxActive: 20
  maxIdle: -1
  minIdle: 6
  maxWaitMillis: 3000
  testOnBorrow: true
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 600000
  minEvictableIdleTimeMillis: -1
  softMinEvictableIdleTimeMillis: 300000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

